service: chris-hutchinson-svelte

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.stage}
  region: ${opt:region, self:custom.region}
  profile: ${opt:profile}
  environment:
    STATIC_RESOURCE_DOMAIN: ${file(./config/${self:provider.stage}.env.yml):static_domain}

functions:
  app:
    handler: handler.app
    events:
      - http:
          path: /
          method: get
      - http:
          path: /index.html
          method: get
  file:
    handler: handler.file
    events:
      - http:
          path: /app.js
          method: get
      - http:
          path: /sw.js
          method: get
      - http:
          path: /main.css
          method: get
      - http:
          path: /manifest.json
          method: get

custom:
  stage: local
  region: eu-west-1

plugins:
  - serverless-offline
  - serverless-plugin-custom-domain