service: chris-hutchinson-svelte

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  profile: chris-machine

functions:
  app:
    handler: handler.app
    events:
      - http:
          path: /
          method: get
      - http:
          path: /index.html
          method: get
  file:
    handler: handler.file
    events:
      - http:
          path: /app.js
          method: get
      - http:
          path: /sw.js
          method: get
      - http:
          path: /main.css
          method: get
      - http:
          path: /manifest.json
          method: get

plugins:
  - serverless-offline