name: Run Axe CLI

on:
  pull_request:
    branches: [main]

jobs:
  capture_vercel_preview_url:
    name: Run Axe CLI
    runs-on: "ubuntu-latest"
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@master
        id: vercel_preview_url
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
      - run: npx wait-on ${{ steps.vercel_preview_url.outputs.url }}
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe ${{ steps.vercel_preview_url.outputs.url }} --exit
