name: Axe CLI

on:
  pull_request:
    branches: [main]

jobs:
  axe_cli:
    name: Axe CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@main
        id: vercel_preview_url
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
      - run: npx wait-on ${{ steps.vercel_preview_url.outputs.url }}
      - name: Run axe
        run: |
          npx axe ${{ steps.vercel_preview_url.outputs.url }}, ${{ steps.vercel_preview_url.outputs.url }}/journal/entry/finding-your-documentation-groove, ${{ steps.vercel_preview_url.outputs.url }}/weeknotes/back-to-work-a-culture-of-feedback-and-learning-corporations-taking-over, ${{ steps.vercel_preview_url.outputs.url }}/photography, ${{ steps.vercel_preview_url.outputs.url }}/about --exit
